### ISSUE TITLE
review

### ISSUE THREAD

**Issue by gnesher** [lanaleyla/CodeeValueExerciseTicTacToe#1]
Well written solution with good use of modules/types.
A few comments:
1. constructor assignment - if you define a property with a private/public in the constructor - it automatically get assigned:
constructor(private rows:number, private columns:number) makes
this.rows=rows; unnecessary
2. indentation - if you're using visual studio code try pressing alt-shift-f it will auto-indent your code making it more readable.

**Comment by lanaleyla** [comment]
fixed the constructors
